[package]
name = "stream-sync"
version = "0.1.0"
edition = "2021"
authors = ["Dr. Sabry Awad <dr.sabry1997@gmail.com>"]

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
futures-util = "0.3.29"
colored = "2.2.0"
